<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddInfoCandidates</name>
   <tag></tag>
   <elementGuidId>389808b3-bb0f-4724-b921-38e293b74874</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[contains(.,'Vacancy')]//parent::div//following-sibling::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[contains(.,'Vacancy')]//parent::div//following-sibling::div</value>
      <webElementGuid>8ae559c9-5c6e-402a-a5e2-19a3af636920</webElementGuid>
   </webElementProperties>
</WebElementEntity>
