<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputContact</name>
   <tag></tag>
   <elementGuidId>1adf9128-4046-4421-9883-a5ee9288c0e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[contains(.,'Contact')]//parent::div//following-sibling::div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[contains(.,'Contact')]//parent::div//following-sibling::div/input</value>
      <webElementGuid>8b3fe55c-c844-4b5b-8e2a-050f5051d5b6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
