<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputEmail</name>
   <tag></tag>
   <elementGuidId>1649e505-adee-4bdb-ad60-378cc3ea0184</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[contains(.,'Email')]//parent::div//following-sibling::div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[contains(.,'Email')]//parent::div//following-sibling::div/input</value>
      <webElementGuid>928968f7-a923-4b08-930f-783b38e012d7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
