<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uploadResume</name>
   <tag></tag>
   <elementGuidId>ed325d98-4edc-4e31-81ce-d18fdadbb7da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type='file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@type='file']</value>
      <webElementGuid>5e187521-cf27-4336-b594-f72b74a295e6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
