<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logout</name>
   <tag></tag>
   <elementGuidId>1229f76b-4a5c-417c-ab68-e54cc3dd06c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[contains(@class,'active')]/ul//a[text()='Logout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[contains(@class,'active')]/ul//a[text()='Logout']</value>
      <webElementGuid>72f0d89b-5204-4455-aa8b-52f7efc920cf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
