<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dateCheckout</name>
   <tag></tag>
   <elementGuidId>6e6bf715-b89c-419a-a454-f58a1cc4cab4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='checkout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='checkout']</value>
      <webElementGuid>97014a57-6c7a-435a-914a-2d8a433cecf5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
