<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dateCheckin</name>
   <tag></tag>
   <elementGuidId>6a6b9318-a96e-4287-914a-4e1f71689dd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='checkin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='checkin']</value>
      <webElementGuid>3558a367-26a2-419a-91e8-aa82e50401e0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
