<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddChildAge</name>
   <tag></tag>
   <elementGuidId>cdea2c1f-f6e4-40f5-a2bb-91156197d572</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[contains(@id,'ages')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[contains(@id,'ages')]</value>
      <webElementGuid>3bdbd353-4eab-4836-afb8-b9ecb92cb4bd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
