<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddNationality</name>
   <tag></tag>
   <elementGuidId>f6027fe1-4344-4b3c-82e4-defb998377e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='nationality']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='nationality']</value>
      <webElementGuid>df9774ce-f0b8-47a1-9164-787d30d972b2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
