<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddTravellers</name>
   <tag></tag>
   <elementGuidId>18ecfddd-c6ca-42b8-8963-b8a3085a7566</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[./p[contains(.,'Travellers')]]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[./p[contains(.,'Travellers')]]</value>
      <webElementGuid>d1259356-a293-42e0-86bb-c659ced9476e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
