<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>optionNationality</name>
   <tag></tag>
   <elementGuidId>b6af8993-935e-48aa-af24-1c340ca72a0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='nationality']/option[text()='${nationality}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='nationality']/option[text()='${nationality}']</value>
      <webElementGuid>05d81949-4a8d-47a2-8310-3837256ebb51</webElementGuid>
   </webElementProperties>
</WebElementEntity>
