<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchResult</name>
   <tag></tag>
   <elementGuidId>9370f02b-64d4-4350-8ce7-d9256728ced5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[contains(text(),'Searching')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[contains(text(),'Searching')]</value>
      <webElementGuid>81368276-8d78-499f-ad9a-8d1a525fa411</webElementGuid>
   </webElementProperties>
</WebElementEntity>
