<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchCityName</name>
   <tag></tag>
   <elementGuidId>e9d179b5-1383-4d20-b6bf-88b0894fbc9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@type='search']</value>
      <webElementGuid>dede0568-3fd1-414d-8a3e-b4182020981a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
