<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectAge</name>
   <tag></tag>
   <elementGuidId>c8db727c-d910-407a-bc3b-5f52fd9c2489</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[contains(@id,'ages')]/option[text()='${age}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[contains(@id,'ages')]/option[text()='${age}']</value>
      <webElementGuid>9f6efa57-b316-4149-9026-877b7c72fcf8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
