<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleDate</name>
   <tag></tag>
   <elementGuidId>f28812b9-1efb-46e9-9242-0ce263667ac6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[./strong[contains(.,'Nights')]]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[./strong[contains(.,'Nights')]]</value>
      <webElementGuid>74b4a815-24ca-4483-b999-edcbfb6d0d05</webElementGuid>
   </webElementProperties>
</WebElementEntity>
