<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleTravellers</name>
   <tag></tag>
   <elementGuidId>5a66e19d-a01f-4b90-8a5a-504ffa450d5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[contains(text(),'Adults')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[contains(text(),'Adults')]</value>
      <webElementGuid>39d6cd3a-dba3-4361-9f30-ccfb191790eb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
