<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDeleteSelected</name>
   <tag></tag>
   <elementGuidId>eaf18c3e-adc7-41b6-a87c-1ecad059955c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[contains(@class,'label-danger')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[contains(@class,'label-danger')]</value>
      <webElementGuid>56d7bfba-7f7a-45bc-a00a-1d35365aaaa5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
