<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleAdminPage</name>
   <tag></tag>
   <elementGuidId>0ef7770c-1862-4a4a-aabe-db621b587dfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h5[contains(@class,'title')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h5[contains(@class,'title')]</value>
      <webElementGuid>759bae5e-5d4b-4b71-a487-19bb51511191</webElementGuid>
   </webElementProperties>
</WebElementEntity>
