<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleAddUserPage</name>
   <tag></tag>
   <elementGuidId>4db78a91-a660-45a8-ba2c-35241b58f9f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h6[contains(@class,'main-title')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h6[contains(@class,'main-title')]</value>
      <webElementGuid>695bc40a-ec7d-4756-bfde-5ef2818acbdb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
