<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnEdit</name>
   <tag></tag>
   <elementGuidId>590ba6cc-ce8d-4343-86ec-20ff8a2f98ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table//tr[./td[./a[text()='old']]]//a[@title='Edit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table//tr[./td[./a[text()='old']]]//a[@title='Edit']</value>
      <webElementGuid>0f23b257-bc6d-4355-bf72-5ad7bb054d73</webElementGuid>
   </webElementProperties>
</WebElementEntity>
