<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAdd</name>
   <tag></tag>
   <elementGuidId>52bd8fd6-75e6-42e0-8a77-6f1253426a8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>354e4c1a-9846-4e92-af0a-9450a8c4cf45</webElementGuid>
   </webElementProperties>
</WebElementEntity>
