<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnClosePopUp</name>
   <tag></tag>
   <elementGuidId>98b31bb6-904b-4bf4-bbcb-957dc24a7a28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'dialog-popup')]//button[contains(@class,'close')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'dialog-popup')]//button[contains(@class,'close')]</value>
      <webElementGuid>800e0e19-bbea-4156-96fb-1385bcb33a28</webElementGuid>
   </webElementProperties>
</WebElementEntity>
