<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDelete</name>
   <tag></tag>
   <elementGuidId>25de104c-582c-4182-8f0b-0f5ab4564022</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'table-card')][${rowIndex}]//button/i[contains(@class,'trash')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'table-card')][${rowIndex}]//button/i[contains(@class,'trash')]</value>
      <webElementGuid>52fc6dcc-a23c-45b1-a83d-2b8679d5a5fb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
