<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnEdit</name>
   <tag></tag>
   <elementGuidId>6108dc38-2f50-4244-a780-f4a2e9d68a04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'table-card')][1]//button/i[contains(@class,'pencil')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'table-card')][1]//button/i[contains(@class,'pencil')]</value>
      <webElementGuid>58080124-979a-4f09-857c-b65bded25ed8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
