<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnFirstSave</name>
   <tag></tag>
   <elementGuidId>efb3a7f4-64e2-4c93-a9aa-d4a2fc276864</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h6[contains(.,'Personal')]//parent::div//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h6[contains(.,'Personal')]//parent::div//button[@type='submit']</value>
      <webElementGuid>2e8d3361-c799-49f5-aa90-9dfeed3052d7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
