<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnPopUpCancel</name>
   <tag></tag>
   <elementGuidId>006f5009-5a33-4335-9709-cc4ea72ef4f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'dialog-popup')]//button[contains(.,'Cancel')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'dialog-popup')]//button[contains(.,'Cancel')]</value>
      <webElementGuid>c9db6018-3ead-4d68-9e56-e5594ffeeb85</webElementGuid>
   </webElementProperties>
</WebElementEntity>
