<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnPopUpDelete</name>
   <tag></tag>
   <elementGuidId>1302f86f-06c4-4b80-81d1-77fca1943e6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'dialog-popup')]//button[contains(.,'Delete')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'dialog-popup')]//button[contains(.,'Delete')]</value>
      <webElementGuid>d064219e-0a69-44fd-97e8-e32361ebb880</webElementGuid>
   </webElementProperties>
</WebElementEntity>
