<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dialogPopUp</name>
   <tag></tag>
   <elementGuidId>7b94f28f-b4dd-4023-b355-56c0de24e0c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'dialog-popup')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'dialog-popup')]</value>
      <webElementGuid>40274fcf-b631-4d51-914d-52f08cd76998</webElementGuid>
   </webElementProperties>
</WebElementEntity>
