<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>editCurrentFile</name>
   <tag></tag>
   <elementGuidId>3625a2d9-b850-46d7-9b36-4cbe4439dad2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'attachment')]//p[not(contains(@class,'hint'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'attachment')]//p[not(contains(@class,'hint'))]</value>
      <webElementGuid>257ea7b3-e20f-4c25-9744-75a36545a13a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
