<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectFileUpload</name>
   <tag></tag>
   <elementGuidId>bb2b661d-6ba3-4e96-9a2a-b5fb10b011fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[text()='Browse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()='Browse']</value>
      <webElementGuid>827f9cb7-6d7c-4872-9fd5-9ab5c3a0516a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
