<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subListPersonalDetails</name>
   <tag></tag>
   <elementGuidId>7f09f1b9-4981-4ac2-9ce4-9004515dc144</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(text(),'Personal')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(text(),'Personal')]</value>
      <webElementGuid>dc210be0-4c85-4484-8815-0cc1c408f42f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
