<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtBodyPopUp</name>
   <tag></tag>
   <elementGuidId>246e3f2a-4012-4041-96c5-dc565009f721</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'dialog-popup')]//div[contains(@class,'text')]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'dialog-popup')]//div[contains(@class,'text')]/p</value>
      <webElementGuid>eef89ee0-c28e-48b7-bad2-886733ba0547</webElementGuid>
   </webElementProperties>
</WebElementEntity>
