<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtHeaderPopUp</name>
   <tag></tag>
   <elementGuidId>5be4931e-218e-42bb-bab3-e26cd022df1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'dialog-popup')]//div[contains(@class,'header')]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'dialog-popup')]//div[contains(@class,'header')]/p</value>
      <webElementGuid>5ff6f935-5cde-41af-8444-325000e7b722</webElementGuid>
   </webElementProperties>
</WebElementEntity>
