<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>monthYear</name>
   <tag></tag>
   <elementGuidId>25094764-a87e-47c0-a255-cca453a9e6a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'datepicker')][${index}]//div[contains(@class,'datepicker-days')]//table//th[contains(@class,'switch')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'datepicker')][${index}]//div[contains(@class,'datepicker-days')]//table//th[contains(@class,'switch')]</value>
      <webElementGuid>e16cca2f-1732-40b5-a661-89e67cc31046</webElementGuid>
   </webElementProperties>
</WebElementEntity>
