<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>numberOfOption</name>
   <tag></tag>
   <elementGuidId>cd8de4c1-1da6-4394-aea9-469a4b95e90b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='${id}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='${id}']</value>
      <webElementGuid>8750f0b5-6fcf-409a-9c09-fe7190c4fd57</webElementGuid>
   </webElementProperties>
</WebElementEntity>
