<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputDateFrom</name>
   <tag></tag>
   <elementGuidId>ef97d203-1780-47a4-8821-fffa7c0d7612</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'date-input')]/input[@placeholder='From']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'date-input')]/input[@placeholder='From']</value>
      <webElementGuid>23222735-724c-494f-86d6-75dcde09687c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
