<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInfoSelected</name>
   <tag></tag>
   <elementGuidId>b1eb2305-85df-447e-aab3-fd2c604542cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[contains(.,'${ddHeader}')]//parent::div//following-sibling::div//div[contains(@class,'text-input')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[contains(.,'${ddHeader}')]//parent::div//following-sibling::div//div[contains(@class,'text-input')]</value>
      <webElementGuid>54da2d77-5e63-4ddc-9375-d3e2069b22c3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
