<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clkItem</name>
   <tag></tag>
   <elementGuidId>bd5a70b1-22d1-4a81-9775-2818bd3c1474</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[contains(@class,'main-menu')]/li[contains(.,'${item}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[contains(@class,'main-menu')]/li[contains(.,'${item}')]</value>
      <webElementGuid>b3c08051-b2ef-4b22-9939-a586373f325a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
