<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>itemMenu</name>
   <tag></tag>
   <elementGuidId>e20c8e8c-4762-4cb0-8b2e-37c659457b49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[contains(@class,'main-menu')]/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[contains(@class,'main-menu')]/li</value>
      <webElementGuid>650f665e-86b2-44f1-b131-555bfcb4d631</webElementGuid>
   </webElementProperties>
</WebElementEntity>
