<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtSearch</name>
   <tag></tag>
   <elementGuidId>a72e6ffa-5100-4321-8f4a-adfb9555bba7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'menu-search')]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'menu-search')]/input</value>
      <webElementGuid>4b1104cb-6f29-4afa-946c-83e31cdde18a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
