<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Downloads</name>
   <tag></tag>
   <elementGuidId>3c1b3a2c-bda0-4d09-ab41-0f27641fd430</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[text()='Downloads']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[text()='Downloads']</value>
      <webElementGuid>c693d8f7-263a-4881-a5ad-c5e84acad0bb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
