<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>listJobTitle</name>
   <tag></tag>
   <elementGuidId>3a528998-ba85-40f5-ba38-e6e230dcbc4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'directory-card')]/p[contains(@class,'directory-card-subtitle')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'directory-card')]/p[contains(@class,'directory-card-subtitle')]</value>
      <webElementGuid>ee5df983-e7e0-4eae-849d-886449fba204</webElementGuid>
   </webElementProperties>
</WebElementEntity>
