<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>listLocation</name>
   <tag></tag>
   <elementGuidId>bc08c361-39bd-4fde-b1ad-6abfcefb21c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'directory-card')]//p[contains(@class,'directory-card-description')][last()]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'directory-card')]//p[contains(@class,'directory-card-description')][last()]</value>
      <webElementGuid>061cb845-a7f2-4ae4-95b9-830fa08d68dd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
