<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectJobTitle</name>
   <tag></tag>
   <elementGuidId>9224f638-b791-45ff-bb28-1059ca16ba11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[contains(text(),'Job')]//parent::div//following-sibling::div//div[contains(@class,'select-dropdown')]/div/span[contains(text(),'Representative')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[contains(text(),'Job')]//parent::div//following-sibling::div//div[contains(@class,'select-dropdown')]/div/span[contains(text(),'Representative')]</value>
      <webElementGuid>290fd0a7-56df-499f-93ec-6994fb461e3a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
