<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnMinusChild</name>
   <tag></tag>
   <elementGuidId>e017c9ef-6628-4f30-ba3d-9b20af524715</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[./input[@id='tours_child']]//i[contains(@class,'minus')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[./input[@id='tours_child']]//i[contains(@class,'minus')]</value>
      <webElementGuid>e3279b41-5051-4913-bfb2-3a3757fb11de</webElementGuid>
   </webElementProperties>
</WebElementEntity>
