<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtChild</name>
   <tag></tag>
   <elementGuidId>fd0532b4-9c11-4979-9e73-2844c1222632</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='tours_child']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='tours_child']</value>
      <webElementGuid>489d9888-7185-4189-98ac-9401cc2c220d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
