<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fullName</name>
   <tag></tag>
   <elementGuidId>435fc49f-1234-4027-b32a-cdca62378758</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='${fullName}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='${fullName}']</value>
      <webElementGuid>5c2170a4-812a-4647-b282-8c54da0fd279</webElementGuid>
   </webElementProperties>
</WebElementEntity>
