<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>postUser</name>
   <tag></tag>
   <elementGuidId>f111b1fb-e189-42ac-8481-c4d7a1205c42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'buzz-newsfeed-post')]//div[contains(@class,'grid-item')][${index}]//p[contains(@class,'emp-name')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'buzz-newsfeed-post')]//div[contains(@class,'grid-item')][${index}]//p[contains(@class,'emp-name')]</value>
      <webElementGuid>5502ffcf-320f-4d68-95a1-d68fdac1e4d0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
