<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleChartLocation</name>
   <tag></tag>
   <elementGuidId>12ea200c-61a2-4eae-a2f6-39d8fcb7d44c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//i[contains(@class,'chart')]//following-sibling::p[contains(.,'Location')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//i[contains(@class,'chart')]//following-sibling::p[contains(.,'Location')]</value>
      <webElementGuid>468d019c-b746-4f6f-917e-1956c1fb98c1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
