<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddFrom</name>
   <tag></tag>
   <elementGuidId>9d3c4ffd-06e8-4875-981c-74f69b4b94d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='autocomplete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='autocomplete']</value>
      <webElementGuid>e909d3d9-8d3c-498d-bae1-d8baf4226915</webElementGuid>
   </webElementProperties>
</WebElementEntity>
