<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>infants</name>
   <tag></tag>
   <elementGuidId>1e32125e-b3c5-4f4a-896f-aae7e5793c48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='finfant']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='finfant']</value>
      <webElementGuid>415faf81-3c87-4c42-a122-0631e7ce3b90</webElementGuid>
   </webElementProperties>
</WebElementEntity>
