<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleTravellers</name>
   <tag></tag>
   <elementGuidId>f5a20cca-5e4f-4be9-a34b-e7db8a23f8e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[./strong[contains(.,'Adults')]]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[./strong[contains(.,'Adults')]]</value>
      <webElementGuid>8fd6bac3-b931-4faa-9de9-8520076f4280</webElementGuid>
   </webElementProperties>
</WebElementEntity>
