<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSearch</name>
   <tag></tag>
   <elementGuidId>85a87691-2d6b-430f-8fcd-369701fdb794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='submit']</value>
      <webElementGuid>6dcd0a6c-7147-4ae1-8432-4db57dd04812</webElementGuid>
   </webElementProperties>
</WebElementEntity>
