<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectDate</name>
   <tag></tag>
   <elementGuidId>ad6feb64-efb6-4ff3-958c-48e7fa2521cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='date']</value>
      <webElementGuid>bdbae156-2da1-49aa-ba56-edba1a822d56</webElementGuid>
   </webElementProperties>
</WebElementEntity>
