<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleAdminPage</name>
   <tag></tag>
   <elementGuidId>f01f9102-de40-4da4-abaf-15112bedbee0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h5[contains(@class,'filter-title')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h5[contains(@class,'filter-title')]</value>
      <webElementGuid>92f4acb8-4a65-450a-bcd3-8c33ec020017</webElementGuid>
   </webElementProperties>
</WebElementEntity>
