<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clkUpload</name>
   <tag></tag>
   <elementGuidId>77452971-0e4b-4d37-9db5-dbe9286a5085</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//table//tr[./td[./a[text()='Admin']]]//a[contains(text(),'Upload')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table//tr[./td[./a[text()='Admin']]]//a[contains(text(),'Upload')]</value>
      <webElementGuid>65a1ea04-d609-4f61-80d6-702bec1999cb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
