<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>srcImage</name>
   <tag></tag>
   <elementGuidId>dc5faba5-c8b9-494a-b8d3-eb808e82c832</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table//tr//a[contains(text(),'admin')]//parent::td//preceding-sibling::td/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table//tr//a[contains(text(),'admin')]//parent::td//preceding-sibling::td/img</value>
      <webElementGuid>be6a8691-f99f-4fc8-adca-bcbf395fdf70</webElementGuid>
   </webElementProperties>
</WebElementEntity>
