<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtImage</name>
   <tag></tag>
   <elementGuidId>b3ab2fb9-5f5f-417e-a4a6-5f63a81c5579</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>94bbc24f-479a-4637-bc3f-d41107160ee1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
