<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>accountsAdmins</name>
   <tag></tag>
   <elementGuidId>c2169223-6093-42b1-878c-6335ac304bd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[text()='Admins']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[text()='Admins']</value>
      <webElementGuid>209c4600-3630-432c-a7d5-996120865730</webElementGuid>
   </webElementProperties>
</WebElementEntity>
