<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconBackgroundColor</name>
   <tag></tag>
   <elementGuidId>56263be2-9c98-4a22-8b5a-aaae22537732</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[./i[text()='${color}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[./i[text()='${color}']]</value>
      <webElementGuid>9d3f0876-735c-49ca-8d38-a67da35b27d3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
