<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconCancelledBookings</name>
   <tag></tag>
   <elementGuidId>f598ab17-f3df-4b82-ba5c-a9668593719d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[./i[text()='clear']]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[./i[text()='clear']]</value>
      <webElementGuid>ccb27652-223c-4b05-aedd-5e24179a8569</webElementGuid>
   </webElementProperties>
</WebElementEntity>
