<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconConfirmedBookings</name>
   <tag></tag>
   <elementGuidId>07815f45-c201-4e81-8fd0-00f6a92baa6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[./i[text()='task_alt']]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[./i[text()='task_alt']]</value>
      <webElementGuid>3da474cb-9b5d-4751-83aa-cdbfa6471828</webElementGuid>
   </webElementProperties>
</WebElementEntity>
