<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconUnpaidBookings</name>
   <tag></tag>
   <elementGuidId>a74434d4-b7cc-462d-ba76-6aa666557ec6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[./i[text()='production_quantity_limits']]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[./i[text()='production_quantity_limits']]</value>
      <webElementGuid>ba1b9229-bf50-40ec-9c87-35e68df84a88</webElementGuid>
   </webElementProperties>
</WebElementEntity>
