<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconPaidBookings</name>
   <tag></tag>
   <elementGuidId>90c8cf70-9365-4b9f-a8ac-5359955d0bb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[./i[text()='credit_score']]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[./i[text()='credit_score']]</value>
      <webElementGuid>70584b39-8b2f-43b9-8476-ba238ad75b96</webElementGuid>
   </webElementProperties>
</WebElementEntity>
